FROM python:3.5

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY mensal.py .

COPY cisco.txt .

COPY id_rsa /root/.ssh/id_rsa

RUN chmod 0600 /root/.ssh/id_rsa

RUN chown root /root/.ssh

CMD [ "python", "./mensal.py"]